# Generated by Django 5.0.4 on 2024-06-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hirework.usermodel'),
        ),
    ]
