# Generated by Django 5.0.4 on 2024-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirework', '0002_alter_usertokenmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
