# Generated by Django 5.0.4 on 2024-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirework', '0004_alter_usertokenmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenmodel',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
