# Generated by Django 5.0.4 on 2024-07-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirework', '0005_alter_usertokenmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='job_shift',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('evening', 'Evening Shift'), ('rotating', 'Rotating Shift'), ('weekend', 'Weekend Shift')], default='day', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetailsmodel',
            name='preferred_job_shift',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('evening', 'Evening Shift'), ('rotating', 'Rotating Shift'), ('weekend', 'Weekend Shift')], default='day', max_length=20),
        ),
    ]
