from django.contrib import admin
from .models import *
# Register your models here. Admin -> Admin@123

admin.site.register(StatesModel)
admin.site.register(CitiesModel)
admin.site.register(IndustriesModel)
admin.site.register(SkillsModel)
admin.site.register(DesignationModel)
admin.site.register(TagsModel)
admin.site.register(BreakReasonModel)
admin.site.register(ScreeningQuestionModel)
admin.site.register(CompanyDetailsModel)
admin.site.register(UserDetailsModel)
admin.site.register(UserReasonModel)
admin.site.register(UserProfessionalDetailsModel)
admin.site.register(UserCertificateModel)
admin.site.register(UserSkillModel)
admin.site.register(UserProjectModel)
admin.site.register(ProjectSkillModel)
admin.site.register(ProfessionalSkillModel)
admin.site.register(UserEducationDetailsModel)
admin.site.register(UserLanguageModel)
admin.site.register(LanguageModel)
admin.site.register(PlansModel)
admin.site.register(BenefitsModel)
admin.site.register(SupplimentalPayModel)
admin.site.register(PeriodModel)
admin.site.register(PlanPeriodModel)
admin.site.register(PlanPurchasedModel)
admin.site.register(JobsModel)
admin.site.register(JobRequriedSkillsModel)
admin.site.register(JobTagsModel)
admin.site.register(JobScreeningQuestionModel)
admin.site.register(JobApplicationModel)
admin.site.register(AnswersModel)
admin.site.register(ChatsModel)
admin.site.register(FavoritesModel)
admin.site.register(UserModel)
admin.site.register(CompanyBenifitsModel)
admin.site.register(CompanySuplimentsModel)
admin.site.register(UserTokenModel)
